name: Scheduled CI

on: 
  schedule:
    # run every day at 2am  
    - cron: '0/7 * * * *'
    - cron: '1/7 * * * *'
    - cron: '2/7 * * * *' 
    - cron: '3/7 * * * *'
    - cron: '4/7 * * * *'
    - cron: '5/7 * * * *'
    - cron: '6/7 * * * *' 


jobs:

  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'feelpp/feelpp' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ok go

  build:
    strategy:
      fail-fast: false
      matrix: 
        include:
#          - {flavor: ubuntu, version: "20.04", dotw: '0'}
          - {flavor: ubuntu, version: "22.04", dotw: '1'}
          - {flavor: ubuntu, version: "22.10", dotw: '2'}
          - {flavor: debian, version: "testing", dotw: '3'}
          - {flavor: debian, version: "sid", dotw: '4'}
          - {flavor: fedora, version: "36", dotw: '5'}
#          - {flavor: fedora, version: "37", dotw: '6'}
    name: Trigger build on ${{ matrix.flavor }}-${{ matrix.version }}
    runs-on: ubuntu-latest
    needs: activate
    steps:
      - 
        if: ${{ github.event.schedule == format('{0}/7 * * * *', matrix.dotw ) }}
        name: "Trigger build [${{ github.event.schedule }}] ${{ matrix.flavor }}-${{ matrix.version }}"
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CR_PAT }}
          repository: feelpp/feelpp
          event-type: trigger-feelpp-build
          client-payload: '{"flavor":"${{ matrix.flavor }}","version":"${{ matrix.version }}"}'

