name: CI

on: push

jobs:

  activate:
    runs-on: self-ubuntu-20.04
    if: |
      github.repository == 'feelpp/feelpp' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ok go

  build:
    runs-on: self-ubuntu-20.04
    needs: activate
    container: ghcr.io/feelpp/feelpp-env:ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Configure feelpp
      run: cmake --preset feelpp
    - name: Build feelpp
      run: cmake --build --preset feelpp -j 10
    - name: Test feelpp
      run: ctest --preset feelpp -j 2
    - name: Download 
      uses: actions/download-artifact@v3
      with:
        # Artifact name
        name: ibat-artifacts
        path: artifacts/
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2        
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    # - 
    #   name: Build container image
    #   uses: docker/build-push-action@v2
    #   with: 
    #     context: artifacts
    #     repository: feelpp/ibat/ham
    #     tags: ghcr.io/feelpp/ibat/ham:latest
    #     file: ./Dockerfile-ham
    #     push: true
